// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v2/table"
)

// Table models.
var (
	DiscordStarboard = table.New(table.Metadata{
		Name: "discord_starboard",
		Columns: []string{
			"emoji_animated",
			"emoji_available",
			"emoji_id",
			"emoji_managed",
			"emoji_require_colons",
			"emoji_roles",
			"message_attachment_ephemeral",
			"message_attachment_filename",
			"message_attachment_height",
			"message_attachment_id",
			"message_attachment_proxy_url",
			"message_attachment_size",
			"message_attachment_url",
			"message_attachment_width",
			"message_author_id",
			"message_author_username",
			"message_content",
			"message_id",
			"message_reaction_count",
			"message_reaction_emoji",
			"sticker_format",
			"sticker_id",
			"sticker_name",
			"user_discriminator",
			"user_global_name",
			"user_username",
		},
		PartKey: []string{
			"message_id",
			"user_global_name",
		},
		SortKey: []string{},
	})
)

type DiscordStarboardStruct struct {
	EmojiAnimated              bool
	EmojiAvailable             bool
	EmojiId                    string
	EmojiManaged               bool
	EmojiRequireColons         bool
	EmojiRoles                 []string
	MessageAttachmentEphemeral bool
	MessageAttachmentFilename  string
	MessageAttachmentHeight    int32
	MessageAttachmentId        string
	MessageAttachmentProxyUrl  string
	MessageAttachmentSize      int32
	MessageAttachmentUrl       string
	MessageAttachmentWidth     int32
	MessageAuthorId            string
	MessageAuthorUsername      string
	MessageContent             string
	MessageId                  string
	MessageReactionCount       int32
	MessageReactionEmoji       string
	StickerFormat              int32
	StickerId                  string
	StickerName                string
	UserDiscriminator          string
	UserGlobalName             string
	UserUsername               string
}
